PROJECT=./example_project
MANAGE=$(PROJECT)/manage.py

help:
	@echo "make commands:"
	@echo "  make help       - this help"
	@echo "  make clean      - remove files generated by setup.py"
	@echo "  make test       - run test suite"
	@echo "  make resetdb    - delete and recreate the database"
	@echo "  make quickstart - setup a dev environment the first time"


clean:
	rm -rf .tox
	rm -rf MANIFEST
	rm -rf build
	rm -rf dist
	rm -rf *.egg-info


test:
#
#   -s    don't capture stdout
#
	python -W ignore::RuntimeWarning $(MANAGE) test django_object_actions -s


# destroy and then recreate your database
resetdb:
	python $(MANAGE) reset_db --router=default --noinput
	python $(MANAGE) syncdb --noinput
	python $(MANAGE) loaddata sample_data


# just a demo of how to get up and running quickly
quickstart: resetdb
	python $(MANAGE) createsuperuser
	python $(MANAGE) runserver


.PHONY: help clean test resetdb quickstart
