PROJECT=./example_project

help:
	@echo "  make help    - this help"
	@echo "  make clean   - remove files generated by distutils"
	@echo "  make test    - run test suite"
	@echo "  make resetdb - delete and recreate the sqlite database"


clean:
	rm -rf MANIFEST
	rm -rf dist
	rm -rf *.egg-info


test:
#
#   -s    don't capture stdout
#
	python $(PROJECT)/manage.py test -s


resetdb:
	$(foreach db, $(wildcard $(PROJECT)/*.sqlite),\
		rm $(db);)
	python $(PROJECT)/manage.py syncdb --noinput


.PHONY: help clean test resetdb
