PROJECT=./example_project
MANAGE=$(PROJECT)/manage.py

help:
	@echo "make commands:"
	@echo "  make help     - this help"
	@echo "  make clean    - remove files generated by distutils"
	@echo "  make test     - run test suite"
	@echo "  make coverage - run coverage"
	@echo "  make resetdb  - delete and recreate the sqlite database"


clean:
	rm -rf .coverage
	rm -rf .tox
	rm -rf MANIFEST
	rm -rf build
	rm -rf dist
	rm -rf *.egg-info


test:
	python -W ignore::RuntimeWarning $(MANAGE) test django_object_actions

coverage:
	coverage erase
	coverage run $(MANAGE) test django_object_actions
	coverage report --show-missing

resetdb:
	python $(MANAGE) reset_db --router=default --noinput
	python $(MANAGE) syncdb --noinput
